### ISSUE TITLE
instructions for putting a kni story online?

### ISSUE THREAD

**Issue by isakgrozny** [kriskowal/kni#5]
first of all, thank you for making this! i'm very excited to play around with it.

secondly, i can't figure out what i'm supposed to do to get a kni game up onto the web. am i missing instructions written clearly somewhere? or am i just too new to these things to figure it out? i don't have much programming knowledge as of yet.

thank you in advance!

**Comment by kriskowal** [comment]
There are a lot of options for how to go forward.

I publish the archery example using a script that generates a Github pages branch that I can push to publish. It uses kni to generate the story state machine as a JSON file. The script uses another tool like Browserify to bundle the engine and the story into a single JavaScript script.

https://github.com/kriskowal/kni/blob/master/build-gh-pages.sh

All of the applications I intend to use kni for will need custom bindings and some web programming. As such, I haven’t created a streamlined approach to publishing a stand-alone story.

It is certainly possible to add a flag to the kni tool that would generate a stand-alone HTML file with a story, including all of its requisite CSS and JavaScript, all as one file. You could put this HTML anywhere. This is something of a tangent to my current goal, which is to ship a particular story with my sister’s illustrations and interactions.

It would also be possible, and in fact straight-forward, to build an editor/player tool in Electron, with a button to generate or publish a stand-alone story. This is a day dream, but I’ve started exploring it.

The next level from there is to produce a service and editor, so folks could publish and even run play tests, collect play test results and coverage, conversion analysis, and all that. This is purely a day dream.

**Comment by Oreolek** [comment]
A pro answer:

1. `git clone https://github.com/kriskowal/kni.git`
2. `cd kni`
3. `npm install`
3. `./npm build` (see note 1)
4. Publish `bundle.js`, `bundle.html` and `examples/archery.json` to web.

Note 1: `npm build` doesn't work on my computer because `bundle` is a Bundler (Ruby) command and browserify is a local npm module.

This answer, of course, is useless for a beginner. Even the pro would need to make a Browserify setup herself. So… wait for a boilerplate, I guess.

**Comment by kriskowal** [comment]
@Oreolek You’re not the first to point out that I should rename `bundle` for that reason. My intention is that the `bundle` command in `node_modules/.bin` should precede the `bundle` on the system in $PATH for the purposes of `npm build`, but that is perhaps naïve. In any case, it is a thing I have the power to change in https://github.com/gutentags/system.

**Comment by kriskowal** [comment]
Published system@1.2.0 with "sysjs" as alternative command name to "bundle".

**Comment by kriskowal** [comment]
I just released version 2.1. You can now `kni story.kni -h story.html` to generate a single page interactive story. There isn’t much fluff, but it’ll do for basic sharing and with a little CSS, you can spruce it up, although keeping your work in sync with the original script may be a bit tedious.

I’m reluctant but open to adding some basic parameters for page title and colors on the command line.

**Comment by kriskowal** [comment]
Circled back and release 2.2 so you can change the title and colors of the generated page with `--html-color` etc.
